version: '3'

services:
  web:
    image: python:3.10-slim-bullseye
    container_name: my-python-app
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: ["python", "app.py"]
